import type { DynamicStrings } from '@azify/aziface-mobile';

export const DYNAMIC_STRINGS: DynamicStrings = {
  action: {
    acceptPhoto: 'Accept Photo',
    confirm: 'Confirm',
    continue: 'Continue',
    imReady: "I'm Ready",
    takePhoto: 'Take Photo',
    ok: 'Ok',
    retakePhoto: 'Retake Photo',
    scanNfc: 'Scan NFC',
    scanNfcCard: 'Scan NFC Card',
    skipNfc: 'Skip NFC',
    tryAgain: 'Try Again',
  },
  accessibility: {
    cancelButton: 'Cancel Button',
    tapGuidance: 'Tap Guidance',
    torchButton: 'Torch Button',
  },
  accessibilityFeedback: {
    face: {
      notOnCamera: 'Not on Camera',
      pointingTooFarLeft: 'Pointing Too Far Left',
      pointingTooFarRight: 'Pointing Too Far Right',
      rotatedTooFarLeft: 'Rotated Too Far Left',
      rotatedTooFarRight: 'Rotated Too Far Right',
      tooFarLeft: 'Too Far Left',
      tooFarRight: 'Too Far Right',
      tooHigh: 'Too High',
      tooLow: 'Too Low',
    },
    holdDeviceToEyeLevel: 'Hold Device To Eye Level',
    movePhoneAway: 'Move Phone Away',
    movePhoneCloser: 'Move Phone Closer',
  },
  camera: {
    initializingCamera: 'Initializing Camera',
    permission: {
      auth: 'Auth',
      enableCamera: 'Enable Camera',
      enroll: 'Enroll',
      header: 'Header',
      launchSettings: 'Launch Settings',
    },
  },
  feedback: {
    centerFace: 'Center Face',
    face: {
      notFound: 'Face Not Found',
      notLookingStraightAhead: 'Not Looking Straight Ahead',
      notUpright: 'Not Upright',
    },
    holdSteady: 'Hold Steady',
    move: {
      phoneAway: 'Move Phone Away',
      phoneCloser: 'Move Phone Closer',
      phoneToEyeLevel: 'Move Phone To Eye Level',
    },
    useEvenLighting: 'Use Even Lighting',
  },
  idScan: {
    additionalReview: 'Additional Review',
    capture: {
      holdSteady: 'Hold Steady',
      idBackInstruction: 'ID Back Instruction',
      idFrontInstruction: 'ID Front Instruction',
      tapToFocus: 'Tap To Focus',
    },
    feedback: {
      flipIdToBack: 'Flip ID To Back',
      flipIdToFront: 'Flip ID To Front',
    },
    nfc: {
      cardStatusFinishedWithError: 'Card Status Finished With Error',
      cardStatusReady: 'Card Status Ready',
      cardStatusStarting: 'Card Status Starting',
      statusDisabled: 'Status Disabled',
      statusFinishedWithError: 'Status Finished With Error',
      statusFinishedWithSuccess: 'Status Finished With Success',
      statusReady: 'Status Ready',
      statusStarting: 'Status Starting',
      statusScanning: 'Status Scanning',
      statusSkipped: 'Status Skipped',
      statusWeakConnection: 'Status Weak Connection',
    },
    ocr: {
      confirmationMainHeader: 'Confirmation Main Header',
      confirmationScroll: 'Confirmation Scroll',
    },
    review: {
      idBackInstruction: 'ID Back Instruction',
      idFrontInstruction: 'ID Front Instruction',
    },
    typeSelectionHeader: 'Type Selection Header',
  },
  instructions: {
    header: {
      primary: 'Primary Header',
      secondary: 'Secondary Header',
    },
    message: {
      primary: 'Primary Message',
      secondary: 'Secondary Message',
    },
  },
  presession: {
    brightenYourEnvironment: 'Brighten Your Environment',
    conditionsTooBright: 'Conditions Too Bright',
    frameYourFace: 'Frame Your Face',
    neutralExpression: 'Neutral Expression',
    orientation: 'Orientation',
    positionFaceStraightInOval: 'Position Face Straight In Oval',
    removeDarkGlasses: 'Remove Dark Glasses',
  },
  result: {
    faceScan: {
      success3d: {
        enrollment: 'Enrollment',
        livenessAndOfficialIdPhoto: 'Liveness And Official ID Photo',
        livenessPriorToIdScan: 'Liveness Prior To ID Scan',
        reverification: 'Reverification',
      },
      upload: 'Upload',
      uploadStillUploading: 'Upload Still Uploading',
    },
    idScan: {
      additionalReviewTag: 'Additional Review Tag',
      skipOrErrorNfc: 'Skip Or Error NFC',
      retry: {
        barcodeNotReadable: 'Barcode Not Readable',
        faceDidNotMatch: 'Face Did Not Match',
        idNotFullyVisible: 'ID Not Fully Visible',
        idTypeNotSupported: 'ID Type Not Supported',
        ocrResultsNotGoodEnough: 'OCR Results Not Good Enough',
      },
      success: {
        additionalReviewTag: 'Additional Review Tag',
        backSide: 'Back Side',
        backSideNfcNext: 'Back Side NFC Next',
        frontSide: 'Front Side',
        frontSideNfcNext: 'Front Side NFC Next',
        frontSideBackNext: 'Front Side Back Next',
        nfc: 'NFC',
        passport: 'Passport',
        passportNfcNext: 'Passport NFC Next',
        userConfirmation: 'User Confirmation',
      },
      unsuccess: 'Unsuccess',
      uploadBackSide: {
        stillUploading: 'Still Uploading',
        uploadCompleteAwaitingProcessing: 'Upload Complete Awaiting Processing',
        uploadCompleteAwaitingResponse: 'Upload Complete Awaiting Response',
        uploadStarted: 'Upload Started',
      },
      uploadFrontSide: {
        stillUploading: 'Still Uploading',
        uploadCompleteAwaitingProcessing: 'Upload Complete Awaiting Processing',
        uploadCompleteAwaitingResponse: 'Upload Complete Awaiting Response',
        uploadStarted: 'Upload Started',
      },
      uploadNfc: {
        stillUploading: 'Still Uploading',
        uploadCompleteAwaitingProcessing: 'Upload Complete Awaiting Processing',
        uploadCompleteAwaitingResponse: 'Upload Complete Awaiting Response',
        uploadStarted: 'Upload Started',
      },
      uploadSkippedNfc: {
        stillUploading: 'Still Uploading',
        uploadCompleteAwaitingProcessing: 'Upload Complete Awaiting Processing',
        uploadCompleteAwaitingResponse: 'Upload Complete Awaiting Response',
        uploadStarted: 'Upload Started',
      },
      uploadUserConfirmedInfo: {
        stillUploading: 'Still Uploading',
        uploadCompleteAwaitingProcessing: 'Upload Complete Awaiting Processing',
        uploadCompleteAwaitingResponse: 'Upload Complete Awaiting Response',
        uploadStarted: 'Upload Started',
      },
    },
    nfcUpload: 'NFC Upload',
    sessionAbort: 'Session Abort',
  },
  retry: {
    header: 'Retry Header',
    idealImageLabel: 'Ideal Image Label',
    subHeader: 'Retry Sub Header',
    yourImageLabel: 'Your Image Label',
    instruction: {
      primary: 'Primary Instruction',
      secondary: 'Secondary Instruction',
      tertiary: 'Tertiary Instruction',
    },
    officialIdPhoto: {
      header: 'Official ID Photo Header',
      instruction: 'Official ID Photo Instruction',
      idealImageLabel: 'Ideal Image Label',
      subHeader: 'Official ID Photo Sub Header',
      yourImageLabel: 'Your Official ID Photo Label',
    },
  },
};
