package com.azify.azifacemobilesdk;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.azify.processors.helpers.ThemeUtils;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.module.annotations.ReactModule;
import com.facebook.react.bridge.ReadableMap;
import android.util.Log;
import org.json.JSONException;
import org.json.JSONObject;
import java.io.IOException;
import java.util.Map;
import okhttp3.Call;
import okhttp3.Callback;
import com.azify.processors.*;
import static java.util.UUID.randomUUID;
import com.facebook.react.modules.core.DeviceEventManagerModule;
import com.facetec.sdk.*;

@ReactModule(name = AzifaceMobileSdkModule.NAME)
public class AzifaceMobileSdkModule extends ReactContextBaseJavaModule {
  private static final ThemeUtils aziThemeUtils = new ThemeUtils();
  public static final String NAME = "AzifaceMobileSdk";
  private final ReactApplicationContext reactContext;
  private boolean isInitialized = false;
  private boolean isSessionPreparingToLaunch = false;
  private String latestExternalDatabaseRefID = "";
  public Promise processorPromise;
  public Processor latestProcessor;
  public FaceTecSessionResult latestSessionResult;
  public FaceTecIDScanResult latestIDScanResult;

  public AzifaceMobileSdkModule(ReactApplicationContext context) {
    super(context);
    reactContext = context;
    aziThemeUtils.setReactContext(context);
  }

  @Override
  @NonNull
  public String getName() {
    return NAME;
  }

  private boolean isDeveloperMode(Map params) {
    if (params.containsKey("isDeveloperMode")) {
      return params.get("isDeveloperMode").toString().equalsIgnoreCase("true");
    }
    return false;
  }

  private void handleFaceTecSDKConfiguration(Map params, ReadableMap headers) {
    try {
      Config.setDevice(params.get("device").toString());
      Config.setUrl(params.get("url").toString());
      Config.setProcessId(params.get("processId").toString());
      Config.setKey(params.get("key").toString());
      Config.setProductionKeyText(params.get("productionKey").toString());
      Config.setHeaders(headers);
    } catch (Exception error) {
      Log.d("Aziface - SDK", "Error while setting FaceTecSDK configuration!");
    }
  }

  @ReactMethod
  public void initializeSdk(ReadableMap params, ReadableMap headers, com.facebook.react.bridge.Callback callback) {
    if (params == null) {
      isInitialized = false;
      callback.invoke(false);
      Log.d("Aziface - SDK", "No parameters provided!");
      return;
    }

    handleFaceTecSDKConfiguration(params.toHashMap(), headers);

    if (Config.hasConfig()) {
      Config.initializeFaceTecSDKFromAutogeneratedConfig(
          reactContext,
          isDeveloperMode(params.toHashMap()),
          new FaceTecSDK.InitializeCallback() {
            @Override
            public void onCompletion(final boolean successful) {
              isInitialized = successful;
              callback.invoke(successful);
              if (!successful) {
                String status = FaceTecSDK.getStatus(reactContext).toString();
                Log.d("Aziface - Status", status);
                Log.d("Aziface - SDK", "FaceTecSDK doesn't initialized!");
              } else {
                Log.d("Aziface - SDK", "FaceTecSDK initialized!");
              }
            }
          });
    } else {
      isInitialized = false;
      callback.invoke(false);
      Log.d("Aziface - SDK", "FaceTecSDK doesn't initialized!");
    }

    this.handleTheme(Config.Theme);
  }

  interface SessionTokenCallback {
    void onSessionTokenReceived(String sessionToken);
  }

  public void getSessionToken(final SessionTokenCallback sessionTokenCallback) {
    okhttp3.Request request = new okhttp3.Request.Builder()
        .headers(Config.getHeaders("GET"))
        .url(Config.BaseURL + "/Process/Session/Token")
        .get()
        .build();

    NetworkingHelpers.getApiClient().newCall(request).enqueue(new Callback() {
      @Override
      public void onFailure(Call call, IOException e) {
        e.printStackTrace();
        Log.d("Aziface - HTTPS", "Exception raised while attempting HTTPS call.");
        if (processorPromise != null) {
          processorPromise.reject("Exception raised while attempting HTTPS call.", "HTTPSError");
        }
      }

      @Override
      public void onResponse(Call call, okhttp3.Response response) throws IOException {
        String responseString = response.body().string();
        response.body().close();
        try {
          JSONObject responseJSON = new JSONObject(responseString);
          JSONObject responseJSONData = responseJSON.getJSONObject("data");

          if (responseJSONData.has("sessionToken")) {
            sessionTokenCallback.onSessionTokenReceived(responseJSONData.getString("sessionToken"));
          } else {
            final String errorMessage = responseJSONData.has("errorMessage")
                ? responseJSONData.getString("errorMessage")
                : "Response JSON is missing sessionToken.";
            if (processorPromise != null) {
              processorPromise.reject(errorMessage, "JSONError");
            }
          }
        } catch (JSONException e) {
          e.printStackTrace();
          if (processorPromise != null) {
            processorPromise.reject("Exception raised while attempting to parse JSON result.", "JSONError");
          }
        }
      }
    });
  }

  public void setLatestSessionResult(FaceTecSessionResult sessionResult) {
    this.latestSessionResult = sessionResult;
  }

  public void setLatestIDScanResult(FaceTecIDScanResult idScanResult) {
    this.latestIDScanResult = idScanResult;
  }

  public void resetLatestResults() {
    this.latestSessionResult = null;
    this.latestIDScanResult = null;
  }

  public void setLatestExternalDatabaseRefID(String externalDatabaseRefID) {
    this.latestExternalDatabaseRefID = externalDatabaseRefID;
  }

  public String getLatestExternalDatabaseRefID() {
    return this.latestExternalDatabaseRefID;
  }

  public void setProcessorPromise(Promise promise) {
    this.processorPromise = promise;
  }

  public void sendEvent(@NonNull String eventName, @Nullable Boolean eventValue) {
    reactContext
        .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
        .emit(eventName, eventValue);
  }

  @ReactMethod
  public void addListener(String eventName) {
  }

  @ReactMethod
  public void removeListeners(Integer count) {
  }

  @ReactMethod
  public void handleTheme(ReadableMap options) {
    ThemeHelpers.setAppTheme(options);
  }

  @ReactMethod
  public void handleEnrollUser(ReadableMap data, Promise promise) {
    setProcessorPromise(promise);
    if (!isInitialized) {
      Log.d("Aziface - SDK", "FaceTecSDK doesn't initialized!");
      this.processorPromise.reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized");
      return;
    }

    isSessionPreparingToLaunch = true;

    getSessionToken(new SessionTokenCallback() {
      @Override
      public void onSessionTokenReceived(String sessionToken) {
        resetLatestResults();
        isSessionPreparingToLaunch = false;
        setLatestExternalDatabaseRefID("android_azify_app_" + randomUUID());
        latestProcessor = new EnrollmentProcessor(sessionToken, reactContext.getCurrentActivity(),
            AzifaceMobileSdkModule.this, data);
      }
    });
  }

  @ReactMethod
  public void handleAuthenticateUser(ReadableMap data, Promise promise) {
    setProcessorPromise(promise);
    if (!isInitialized) {
      Log.d("Aziface - SDK", "FaceTecSDK doesn't initialized!");
      this.processorPromise.reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized");
      return;
    }

    isSessionPreparingToLaunch = true;

    getSessionToken(new SessionTokenCallback() {
      @Override
      public void onSessionTokenReceived(String sessionToken) {
        resetLatestResults();
        isSessionPreparingToLaunch = false;
        latestProcessor = new AuthenticateProcessor(sessionToken, reactContext.getCurrentActivity(),
            AzifaceMobileSdkModule.this, data);
      }
    });
  }

  @ReactMethod
  public void handlePhotoIDMatch(ReadableMap data, Promise promise) {
    setProcessorPromise(promise);
    if (!isInitialized) {
      Log.d("Aziface - SDK", "FaceTecSDK doesn't initialized!");
      this.processorPromise.reject("FaceTecSDK doesn't initialized!", "FaceTecDoenstInitialized");
      return;
    }

    isSessionPreparingToLaunch = true;

    getSessionToken(new SessionTokenCallback() {
      @Override
      public void onSessionTokenReceived(String sessionToken) {
        resetLatestResults();
        isSessionPreparingToLaunch = false;
        setLatestExternalDatabaseRefID("android_azify_app_" + randomUUID());
        latestProcessor = new PhotoIDMatchProcessor(sessionToken, reactContext.getCurrentActivity(),
            AzifaceMobileSdkModule.this, data);
      }
    });
  }

}
