name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  common:
    name: Lint and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive
          token: ${{ secrets.GH_TOKEN_V2 }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build and Publish facetec-aar
        run: |
          cd external/facetec-aar
          gradle publish
      - name: Verify that facetec-sdk was published
        run: |
          ls -R external/facetec-aar/build/repo/com/azify/facetec/facetec-sdk/9.7.47 || echo "Not found"

    # - name: PR Semantic Release Check
    #   uses: amannn/action-semantic-pull-request@v3.1.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN_V2 }}

    #   with:
    #     types: |
    #       fix
    #       feat
    #       ci
    #       chore

    # - name: Installing dependencies
    #   run: |
    #     npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
    #     npm ci

    # - name: Run build
    #   run: npm run prepack

    # - name: Run example
    #   run: cd example && npm install && cd android && ./gradlew assembleRelease
